repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
        # terraform-docs adds trailing whitespace in some cases
        exclude: ^.*\.md$

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_tfsec
        args: ["--args", "--exclude-downloaded-modules"]

#  - repo: https://github.com/golangci/golangci-lint
#    rev: v1.63.4
#    hooks:
#      - id: golangci-lint
#        args: [--timeout=3m]
