version: 2.1

jobs:
  pre-commit:
    docker:
      - image: ${AWS_ECR_ACCOUNT_URL}/circleci-terraform:tfenv-3.0.0
        aws_auth:
          aws_access_key_id: $PIPELINE_ACCESS_KEY_ID
          aws_secret_access_key: $PIPELINE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: |
            tfenv use min-required
            terraform init
            pre-commit run -a
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - '~/.cache/pre-commit'

workflows:
  terraform:
    jobs:
      - pre-commit:
          context: aws