name: Tag Release

on:
  push:
    paths:
      - version
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: onemedical/action-general-autotag@1.1.0
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          source_file: 'version'
          extraction_regex: "(\\d+\\.\\d+\\.\\d+)"
          tag_format: 'v{version}'
