# This is the workflow that calls the reusable Tag and Release Terraform Module workflow,
# which will create a new tag based on a value in version file and create a GitHub release.
---
name: 🏷 Tag and Release


on:
  push:
    paths:
      - version
    branches: [main, master]


permissions:
  # Required for workflows in private repositories.
  contents: write


jobs:
  # Call the reusable workflow locally
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check out code
        uses: actions/checkout@v3

      - name: 🏷 Create a tag
        id: create-tag
        uses: butlerlogic/action-autotag@stable
        with:
          strategy: regex
          root: "version"
          regex_pattern: "(\\d+\\.\\d+\\.\\d+)"
          tag_prefix: "v"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 🦄 Create a release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ steps.create-tag.outputs.tagname }}
          token: ${{ secrets.GITHUB_TOKEN }}
