# This is the workflow that calls the reusable Tag and Release Terraform Module workflow,
# which will create a new tag based on a value in version file and create a GitHub release.
---
name: 🏷 Tag and Release


on:
  push:
    paths:
      - version
    branches: [main, master]


permissions:
  # Required for workflows in private repositories.
  contents: write


jobs:
  # Call the reusable workflow locally
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - name: Call tag and release terraform module workflow
        uses: ./.github/workflows/reusable-tag-and-release-terraform-module.yaml
